var amqp = require('amqplib/callback_api');


amqp.connect('amqp://localhost', function (error0, connection) {
    if(error0) throw error0
    connection.createChannel(function (error1, channel) {
        if(error1) throw error1

        let queue = 'task_queue2'
        let msg = process.argv.slice(2).join(' ') || "Hello World!";

        channel.assertQueue(queue,{
            durable: true
        });
        let i = 0
        setInterval(() => {
            if(i)
                channel.sendToQueue(queue, Buffer.from(i++ + ''), {
                    persistent: true
                })
            else
                channel.sendToQueue(queue, Buffer.from(i++ + 'LoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREMLoremLOrEMLOREMLOREMLOREMLOREM'), {
                    persistent: true
                });
        },0)
    })

    // setTimeout(() => {
    //     connection.close()
    //     // process.exit(0)
    // },1000)

});